/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import enums.actions.ActionMenu;
import controller.PrincipalControlador;
import javax.swing.JTable;

/**
 *
 * @author emedina
 */
public class PrincipalUI extends javax.swing.JFrame {
    PrincipalControlador controlador;
    /**
     * Creates new form PrincipalUI
     */
    public PrincipalUI() {
        initComponents();
        controlador = new PrincipalControlador(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLatePayment = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNewTeacher = new javax.swing.JMenuItem();
        jMenuStudent = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuSeatchTeacher = new javax.swing.JMenuItem();
        jMenuSearchStudent = new javax.swing.JMenuItem();
        jMenuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableLatePayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableLatePayment);

        jMenu1.setText("Nuevo");

        jMenuNewTeacher.setText("Profesor");
        jMenuNewTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewTeacherActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNewTeacher);

        jMenuStudent.setText("Estudiante");
        jMenuStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStudentActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuStudent);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Buscar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuSeatchTeacher.setText("Profesor");
        jMenuSeatchTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSeatchTeacherActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSeatchTeacher);

        jMenuSearchStudent.setText("Estudiante");
        jMenu2.add(jMenuSearchStudent);

        jMenuBar1.add(jMenu2);

        jMenuLogout.setText("Salir");
        jMenuBar1.add(jMenuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNewTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewTeacherActionPerformed
        controlador.menuAction(ActionMenu.NEWTEACHER);
    }//GEN-LAST:event_jMenuNewTeacherActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuSeatchTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSeatchTeacherActionPerformed
        controlador.menuAction(ActionMenu.SEARCHTEACHER);
    }//GEN-LAST:event_jMenuSeatchTeacherActionPerformed

    private void jMenuStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStudentActionPerformed
        controlador.menuAction(ActionMenu.SEARCHTEACHER);
    }//GEN-LAST:event_jMenuStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JMenuItem jMenuNewTeacher;
    private javax.swing.JMenuItem jMenuSearchStudent;
    private javax.swing.JMenuItem jMenuSeatchTeacher;
    private javax.swing.JMenuItem jMenuStudent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLatePayment;
    // End of variables declaration//GEN-END:variables

    public JTable getjTableLatePayment() {
        return jTableLatePayment;
    }

    public void setjTableLatePayment(JTable jTableLatePayment) {
        this.jTableLatePayment = jTableLatePayment;
    }
}
