/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.toedter.calendar.JDateChooser;
import modelo.dao.TeacherDao;
import ia.util.Picture;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import controlador.TeacherAbcControlador;
import enums.helper.EntryPoint;
import javax.swing.JButton;
/**
 *
 * @author emedina
 */
public class TeacherUI_ABC extends javax.swing.JFrame {
    private TeacherDao teacherDao;
    private TeacherAbcControlador controlador;
    
    /**
     * Creates new form TeacherABC with a new teacherDao
     */
    public TeacherUI_ABC() {
        initComponents();
        setLocationRelativeTo(null);
        teacherDao = new TeacherDao();
        controlador = new TeacherAbcControlador(this,EntryPoint.NEW);
        initValues();
    }
    
    /**
     * Creates new form TeacherABC with a teacherDao object 
     * @param teacherDao
     */
    public TeacherUI_ABC(TeacherDao teacherDao){
        initComponents();
        setLocationRelativeTo(null);
        this.teacherDao = teacherDao;
        controlador = new TeacherAbcControlador(this,EntryPoint.SEARCH);
        initValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextLastName1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextLastName2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextAddress = new javax.swing.JTextField();
        jTextPhoneHome = new javax.swing.JTextField();
        jTextPhonePersonal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextEmailPersonal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextEmailWork = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextCurp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxLevel = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaExperience = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonLoadImage = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jDateStart = new com.toedter.calendar.JDateChooser();
        jDateEnd = new com.toedter.calendar.JDateChooser();
        jPanelPicture = new javax.swing.JPanel();
        jButtonErasePicture = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonClear = new javax.swing.JButton();
        jTextPassword = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemPrincipal = new javax.swing.JMenuItem();
        jMenuItemSearch = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nombre");

        jTextName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNameKeyTyped(evt);
            }
        });

        jLabel2.setText("Apellido Paterno");

        jTextLastName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextLastName1KeyTyped(evt);
            }
        });

        jLabel3.setText("Apellido Materno");

        jTextLastName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLastName2ActionPerformed(evt);
            }
        });
        jTextLastName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextLastName2KeyTyped(evt);
            }
        });

        jLabel4.setText("Direccion");

        jTextAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAddressKeyTyped(evt);
            }
        });

        jTextPhoneHome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPhoneHomeKeyTyped(evt);
            }
        });

        jTextPhonePersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPhonePersonalKeyTyped(evt);
            }
        });

        jLabel5.setText("No. Telefonico");

        jLabel6.setText("Telefono celular");

        jLabel8.setText("Email personal");

        jTextEmailPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextEmailPersonalKeyTyped(evt);
            }
        });

        jLabel9.setText("Email laboral");

        jTextEmailWork.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextEmailWorkKeyTyped(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setText("Curp");

        jTextCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCurpActionPerformed(evt);
            }
        });
        jTextCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCurpKeyTyped(evt);
            }
        });

        jLabel10.setText("Cedula");

        jTextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulaActionPerformed(evt);
            }
        });

        jLabel14.setText("Nivel");

        jComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2" }));

        jLabel15.setText("Estatus");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2" }));

        jLabel16.setText("Experiencia");

        jTextAreaExperience.setColumns(20);
        jTextAreaExperience.setRows(5);
        jScrollPane1.setViewportView(jTextAreaExperience);

        jLabel11.setText("Fecha Ingreso");

        jLabel12.setText("Fecha Salida");

        jButtonLoadImage.setText("Cargar imagen");
        jButtonLoadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadImageActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanelPicture.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelPictureLayout = new javax.swing.GroupLayout(jPanelPicture);
        jPanelPicture.setLayout(jPanelPictureLayout);
        jPanelPictureLayout.setHorizontalGroup(
            jPanelPictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        jPanelPictureLayout.setVerticalGroup(
            jPanelPictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jButtonErasePicture.setText("Borrar imagen");
        jButtonErasePicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonErasePictureActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Agregar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Actualizar");

        jButtonDelete.setText("Eliminar");

        jButtonClear.setText("Limpiar");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabel13.setText("Contraseña");

        jMenu1.setText("Opciones");

        jMenuItemPrincipal.setText("Principal");
        jMenuItemPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrincipalActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPrincipal);

        jMenuItemSearch.setText("Buscar");
        jMenu1.add(jMenuItemSearch);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonAdd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonUpdate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonDelete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonClear))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel13))
                                            .addGap(30, 30, 30)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextEmailWork, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextEmailPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextLastName2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextPhoneHome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextPhonePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jTextCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextCedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBoxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jButtonLoadImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jDateStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jDateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonErasePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdd)
                            .addComponent(jButtonUpdate)
                            .addComponent(jButtonDelete)
                            .addComponent(jButtonClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2)
                                                .addComponent(jTextLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextLastName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextPhoneHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextPhonePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8)
                                                .addComponent(jTextEmailPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel9)
                                                .addComponent(jTextEmailWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(7, 7, 7)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jTextCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel10)
                                                .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jPanelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel15)
                                                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(5, 5, 5)
                                        .addComponent(jButtonLoadImage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonErasePicture)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextLastName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLastName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLastName2ActionPerformed

    private void jTextCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCurpActionPerformed

    private void jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulaActionPerformed

    private void jButtonLoadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadImageActionPerformed
        controlador.loadPicture();
    }//GEN-LAST:event_jButtonLoadImageActionPerformed

    private void jButtonErasePictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonErasePictureActionPerformed
        controlador.erasePicture();
    }//GEN-LAST:event_jButtonErasePictureActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        controlador.clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTextNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNameKeyTyped
        if (this.jTextName.getText().length() == 40) {
            evt.consume();
        }
        if (!Character.isLetter(evt.getKeyChar())) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextNameKeyTyped

    private void jTextLastName1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextLastName1KeyTyped
        if (this.jTextLastName1.getText().length() == 40) {
            evt.consume();
        }
        if (!Character.isLetter(evt.getKeyChar())) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextLastName1KeyTyped

    private void jTextLastName2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextLastName2KeyTyped
        if (this.jTextLastName2.getText().length() == 40) {
            evt.consume();
        }
        if (!Character.isLetter(evt.getKeyChar())) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextLastName2KeyTyped

    private void jTextAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAddressKeyTyped
        if (this.jTextAddress.getText().length() == 100){
            evt.consume();
        }
    }//GEN-LAST:event_jTextAddressKeyTyped

    private void jTextPhoneHomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPhoneHomeKeyTyped
        if (this.jTextPhoneHome.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextPhoneHomeKeyTyped

    private void jTextPhonePersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPhonePersonalKeyTyped
        if (this.jTextPhonePersonal.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextPhonePersonalKeyTyped

    private void jTextEmailWorkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmailWorkKeyTyped
         if (this.jTextEmailWork.getText().length() == 100) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextEmailWorkKeyTyped

    private void jTextEmailPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmailPersonalKeyTyped
         if (this.jTextEmailPersonal.getText().length() == 100) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextEmailPersonalKeyTyped

    private void jTextCurpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCurpKeyTyped
         if (this.jTextCurp.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextCurpKeyTyped

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        controlador.insertData();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jMenuItemPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrincipalActionPerformed
        controlador.returnToPrincpal();
    }//GEN-LAST:event_jMenuItemPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherUI_ABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherUI_ABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherUI_ABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherUI_ABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherUI_ABC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonErasePicture;
    private javax.swing.JButton jButtonLoadImage;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxLevel;
    private javax.swing.JComboBox jComboBoxStatus;
    private com.toedter.calendar.JDateChooser jDateEnd;
    private com.toedter.calendar.JDateChooser jDateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemPrincipal;
    private javax.swing.JMenuItem jMenuItemSearch;
    private javax.swing.JPanel jPanelPicture;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextArea jTextAreaExperience;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextCurp;
    private javax.swing.JTextField jTextEmailPersonal;
    private javax.swing.JTextField jTextEmailWork;
    private javax.swing.JTextField jTextLastName1;
    private javax.swing.JTextField jTextLastName2;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPassword;
    private javax.swing.JTextField jTextPhoneHome;
    private javax.swing.JTextField jTextPhonePersonal;
    // End of variables declaration//GEN-END:variables
    private int id; //Pk 
    private String path;
    
    private void initValues(){
        id = teacherDao.getId();
        jTextName.setText(teacherDao.getName());
        jTextLastName1.setText(teacherDao.getFirstLastName());
        jTextLastName2.setText(teacherDao.getSecondLastName());
        jTextAddress.setText(teacherDao.getAddress());
        jTextPhoneHome.setText(teacherDao.getHomePhone());
        jTextPhonePersonal.setText(teacherDao.getPersonalPhone());
        jTextEmailPersonal.setText(teacherDao.getPersonalEmail());
        jTextEmailWork.setText(teacherDao.getWorkEmail());
        jTextCurp.setText(teacherDao.getCurp());
        jTextCedula.setText(teacherDao.getCedula());
        jTextPassword.setText(teacherDao.getPassword());
        jTextAreaExperience.setText(teacherDao.getExperience());
        jDateStart.setDate(teacherDao.getStartDate());
        jDateEnd.setDate(teacherDao.getEndDate());
        jComboBoxLevel.setSelectedIndex(teacherDao == null ? 0 : teacherDao.getLevel());
        jComboBoxStatus.setSelectedIndex(teacherDao == null ? 0 : teacherDao.getStatus());
        if(teacherDao.getPicture() == null || teacherDao.getPicture().isEmpty()) 
        {
            jPanelPicture.removeAll();
            jPanelPicture.repaint();
        } 
        else
        {
            Picture picture = new Picture(jPanelPicture.getWidth(),jPanelPicture.getHeight(),teacherDao.getPicture());
            jPanelPicture.removeAll();
            jPanelPicture.add(picture);
            jPanelPicture.repaint();
        }
    }

    public int getId() {
        return id;
    }

    public JComboBox getjComboBoxLevel() {
        return jComboBoxLevel;
    }

    public void setjComboBoxLevel(JComboBox jComboBoxLevel) {
        this.jComboBoxLevel = jComboBoxLevel;
    }

    public JComboBox getjComboBoxStatus() {
        return jComboBoxStatus;
    }

    public void setjComboBoxStatus(JComboBox jComboBoxStatus) {
        this.jComboBoxStatus = jComboBoxStatus;
    }

    public JDateChooser getjDateEnd() {
        return jDateEnd;
    }

    public void setjDateEnd(JDateChooser jDateEnd) {
        this.jDateEnd = jDateEnd;
    }

    public JDateChooser getjDateStart() {
        return jDateStart;
    }

    public void setjDateStart(JDateChooser jDateStart) {
        this.jDateStart = jDateStart;
    }

    public JPanel getjPanelPicture() {
        return jPanelPicture;
    }

    public void setjPanelPicture(JPanel jPanelPicture) {
        this.jPanelPicture = jPanelPicture;
    }

    public JTextField getjTextAddress() {
        return jTextAddress;
    }

    public void setjTextAddress(JTextField jTextAddress) {
        this.jTextAddress = jTextAddress;
    }

    public JTextArea getjTextAreaExperience() {
        return jTextAreaExperience;
    }

    public void setjTextAreaExperience(JTextArea jTextAreaExperience) {
        this.jTextAreaExperience = jTextAreaExperience;
    }

    public JTextField getjTextCedula() {
        return jTextCedula;
    }

    public void setjTextCedula(JTextField jTextCedula) {
        this.jTextCedula = jTextCedula;
    }

    public JTextField getjTextCurp() {
        return jTextCurp;
    }

    public void setjTextCurp(JTextField jTextCurp) {
        this.jTextCurp = jTextCurp;
    }

    public JTextField getjTextEmailPersonal() {
        return jTextEmailPersonal;
    }

    public void setjTextEmailPersonal(JTextField jTextEmailPersonal) {
        this.jTextEmailPersonal = jTextEmailPersonal;
    }

    public JTextField getjTextEmailWork() {
        return jTextEmailWork;
    }

    public void setjTextEmailWork(JTextField jTextEmailWork) {
        this.jTextEmailWork = jTextEmailWork;
    }

    public JTextField getjTextLastName1() {
        return jTextLastName1;
    }

    public void setjTextLastName1(JTextField jTextLastName1) {
        this.jTextLastName1 = jTextLastName1;
    }

    public JTextField getjTextLastName2() {
        return jTextLastName2;
    }

    public void setjTextLastName2(JTextField jTextLastName2) {
        this.jTextLastName2 = jTextLastName2;
    }

    public JTextField getjTextName() {
        return jTextName;
    }

    public void setjTextName(JTextField jTextName) {
        this.jTextName = jTextName;
    }

    public JTextField getjTextPhoneHome() {
        return jTextPhoneHome;
    }

    public void setjTextPhoneHome(JTextField jTextPhoneHome) {
        this.jTextPhoneHome = jTextPhoneHome;
    }

    public JTextField getjTextPhonePersonal() {
        return jTextPhonePersonal;
    }

    public void setjTextPhonePersonal(JTextField jTextPhonePersonal) {
        this.jTextPhonePersonal = jTextPhonePersonal;
    }

    public JTextField getjTextPassword() {
        return jTextPassword;
    }

    public void setjTextPassword(JTextField jTextPassword) {
        this.jTextPassword = jTextPassword;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public JButton getjButtonAdd() {
        return jButtonAdd;
    }

    public void setjButtonAdd(JButton jButtonAdd) {
        this.jButtonAdd = jButtonAdd;
    }

    public JButton getjButtonDelete() {
        return jButtonDelete;
    }

    public void setjButtonDelete(JButton jButtonDelete) {
        this.jButtonDelete = jButtonDelete;
    }

    public JButton getjButtonUpdate() {
        return jButtonUpdate;
    }

    public void setjButtonUpdate(JButton jButtonUpdate) {
        this.jButtonUpdate = jButtonUpdate;
    }
    
}